<a href="https://colab.research.google.com/github/Kashish-Shukla18/Machine_learning/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [58]:
df = sns.load_dataset('iris')

In [59]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [60]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X=df.drop('species',axis=1)
y=df['species']

In [63]:
X_train, X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.33,random_state=42
)

In [64]:
from sklearn.neighbors import KNeighborsClassifier

In [65]:
model_knn=KNeighborsClassifier(n_neighbors=15)

In [66]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [67]:
model_knn.score(X_test,y_test)

1.0

In [68]:
from sklearn.svm import SVC

In [69]:
model_svm=SVC(gamma='auto')

In [70]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [71]:
model_svm.score(X_test,y_test)

1.0

Let's Use Grid Search CV(Cross Validation)

In [72]:
from sklearn.model_selection import GridSearchCV

In [73]:
classifier=GridSearchCV((model_svm),{'C':[1,10,20,30],'kernel':['rbf','linear'],},cv=5,return_train_score=False)

In [74]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [75]:
classifier.cv_results_

{'mean_fit_time': array([0.00421305, 0.00279131, 0.00250506, 0.00241871, 0.0024744 ,
        0.00255232, 0.00340643, 0.00277719]),
 'std_fit_time': array([1.03362494e-03, 3.03790390e-04, 6.68672948e-05, 1.31827788e-04,
        1.05792704e-04, 2.92208612e-04, 8.97530959e-04, 2.93456551e-04]),
 'mean_score_time': array([0.00299792, 0.00205488, 0.00184965, 0.0017828 , 0.00180235,
        0.00206213, 0.00229158, 0.00203767]),
 'std_score_time': array([6.56547911e-04, 1.85110089e-04, 5.62338409e-05, 2.52973685e-05,
        1.07747536e-04, 2.97536544e-04, 3.32509755e-04, 1.48111225e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [76]:
results=pd.DataFrame(classifier.cv_results_)

In [77]:
results

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.004213      0.001034  ...        0.016330                1
1       0.002791      0.000304  ...        0.016330                1
2       0.002505      0.000067  ...        0.016330                1
3       0.002419      0.000132  ...        0.038873                4
4       0.002474      0.000106  ...        0.036515                5
5       0.002552      0.000292  ...        0.042164                6
6       0.003406      0.000898  ...        0.038873                7
7       0.002777      0.000293  ...        0.048990                7

[8 rows x 15 columns]

In [78]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

RANDOM SEARCH CV

In [79]:
from sklearn.model_selection import RandomizedSearchCV

In [81]:
classifier_r=RandomizedSearchCV((model_svm),{'C':[1,10,20,30],'kernel':['rbf','linear'],},cv=5,return_train_score=False,n_iter=4)

In [82]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [83]:
results=pd.DataFrame(classifier_r.cv_results_)

In [84]:
results

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.003872      0.000267  ...        0.038873                2
1       0.004158      0.000503  ...        0.016330                1
2       0.008637      0.002907  ...        0.042164                4
3       0.020005      0.003717  ...        0.036515                3

[4 rows x 15 columns]

In [85]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10       linear         0.973333
1       10          rbf         0.980000
2       20       linear         0.966667
3       20          rbf         0.966667