<a href="https://colab.research.google.com/github/Kashish-Shukla18/Machine_learning/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [32]:
df = sns.load_dataset('iris')

In [33]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X=df.drop('species',axis=1)
y=df['species']

In [37]:
X_train, X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.33,random_state=42
)

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [39]:
model_knn=KNeighborsClassifier(n_neighbors=15)

In [40]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [41]:
model_knn.score(X_test,y_test)

1.0

In [42]:
from sklearn.svm import SVC

In [43]:
model_svm=SVC(gamma='auto')

In [44]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [45]:
model_svm.score(X_test,y_test)

0.98

Let's Use Grid Search CV(Cross Validation)

In [46]:
from sklearn.model_selection import GridSearchCV

In [49]:
classifier=GridSearchCV((model_svm),{'C':[1,10,20,30],'kernel':['rbf','linear'],},cv=5,return_train_score=False)

In [52]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [53]:
classifier.cv_results_

{'mean_fit_time': array([0.00289674, 0.00272031, 0.0047061 , 0.00537176, 0.00239873,
        0.0025362 , 0.00285249, 0.00241199]),
 'std_fit_time': array([4.23980059e-04, 2.44151912e-04, 1.33046949e-03, 5.39204206e-03,
        6.08622441e-05, 5.37568287e-05, 4.58706030e-04, 8.24019036e-05]),
 'mean_score_time': array([0.002531  , 0.00204668, 0.00320592, 0.00197687, 0.00175223,
        0.00209785, 0.00212507, 0.00174441]),
 'std_score_time': array([9.70077653e-04, 1.67544225e-04, 2.70049542e-04, 1.55585001e-04,
        4.47819911e-05, 5.04059054e-04, 2.55258480e-04, 2.79894070e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [54]:
results=pd.DataFrame(classifier.cv_results_)

In [55]:
results

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002897      0.000424  ...        0.016330                1
1       0.002720      0.000244  ...        0.016330                1
2       0.004706      0.001330  ...        0.016330                1
3       0.005372      0.005392  ...        0.038873                4
4       0.002399      0.000061  ...        0.036515                5
5       0.002536      0.000054  ...        0.042164                6
6       0.002852      0.000459  ...        0.038873                7
7       0.002412      0.000082  ...        0.048990                7

[8 rows x 15 columns]

In [56]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000